# Generated by Django 4.0.5 on 2022-11-01 16:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('curso', '0001_initial'),
        ('orientador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=150)),
                ('ano_documento', models.IntegerField(default=None, verbose_name='Ano do Tcc')),
                ('resumo', models.TextField(default=None, max_length=150)),
                ('tcc', models.FileField(upload_to='livros/', verbose_name='TCC')),
                ('palavras_chave', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientador.orientador')),
            ],
        ),
    ]
