# Generated by Django 4.0.5 on 2022-11-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='tcc',
            field=models.FileField(upload_to='uploads/tccs/', verbose_name='TCC'),
        ),
    ]
