# Generated by Django 4.0.5 on 2022-11-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=150)),
                ('ultimo_nome', models.CharField(max_length=150)),
                ('link_currilo_lattes', models.CharField(max_length=150)),
            ],
        ),
    ]
